# Generated by Django 4.0.3 on 2022-03-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_book_slug_alter_book_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ISBN',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pages',
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(blank=True, choices=[('V', 'voice'), ('T', 'text')], max_length=1),
        ),
    ]
