# Generated by Django 4.0.3 on 2022-03-30 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_book_isbn_remove_book_pages_alter_book_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
